trigger:
  branches:
    include:
      - main
pr: none

resources:
  repositories:
    - repository: templates
      type: github
      name: microsoft/vscode-engineering
      ref: main
      endpoint: Monaco

parameters:
  - name: publishExtension
    displayName: 🚀 Publish Extension
    type: boolean
    default: false

extends:
  template: azure-pipelines/extension/stable.yml@templates
  parameters:
    publishExtension: ${{ parameters.publishExtension }}
    buildSteps:
      - script: yarn install --frozen-lockfile
        displayName: Install dependencies

      - script: yarn run package-web
        displayName: Compile
    tsa:
      config:
        areaPath: 'Visual Studio Code Web Extensions'
        serviceTreeID: '1788a767-5861-45fb-973b-c686b67c5541'
      enabled: true
